In [5]:
import tensorflow as tf

In [36]:
# 1. Crear capa de vectorización de texto
vectorize_layer = tf.keras.layers.TextVectorization(
    max_tokens=1000,
    output_mode='int',
    output_sequence_length=5
)

# 2. Preparar un "vocabulario - corpus" con algunos ejemplos
text_data = tf.constant([
    "hola mundo",
    "buenos días que haces",
    "hola amigo",
    "mundo abierto"
])



la línea token_ids = vectorize_layer(input_text) está efectivamente obteniendo los IDs del input_text basándose en el vocabulario aprendido del text_data. Es como una "traducción" de palabras a números utilizando el diccionario creado a partir del corpus.

In [41]:
# 3. entrenar o Adaptar la capa a esos textos - vectoriza los tokens del corpus
vectorize_layer.adapt(text_data)

# 4. Vectorizar tu entrada - vectoriza los tokens de entrada
input_text = tf.constant(["hola mundo"])
token_ids = vectorize_layer(input_text)

In [43]:
# 5. Crear la capa de embedding (dim 4 por ejemplo) - dimension de los embedings
embedding_layer = tf.keras.layers.Embedding(input_dim=1000, output_dim=4)

# 6. Obtener los embeddings
embedded_output = embedding_layer(token_ids)

# Mostrar resultados
print("Texto:", input_text.numpy())
print("Token IDs:", token_ids.numpy())

#muestra conde aparece los tokens de la frase de entrada en el corpus
print(text_data[3])
print(text_data[2])
print(text_data[0])

print("Embeddings:\n", embedded_output.numpy())


Texto: [b'hola mundo']
Token IDs: [[3 2 0 0 0]]
tf.Tensor(b'mundo abierto', shape=(), dtype=string)
tf.Tensor(b'hola amigo', shape=(), dtype=string)
tf.Tensor(b'hola mundo', shape=(), dtype=string)
Embeddings:
 [[[ 0.04369533  0.01390279 -0.01963254  0.00200937]
  [-0.0456666   0.03178049 -0.02291701  0.02356335]
  [-0.0156853   0.0494352   0.01687149  0.00582154]
  [-0.0156853   0.0494352   0.01687149  0.00582154]
  [-0.0156853   0.0494352   0.01687149  0.00582154]]]
